# Keep the contributors list updated in the README.md file
name: update-contributors

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-contributors"
  update-contributors:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the update-contributors.sh script
      - name: update README.md
        run: wget -O - https://raw.githubusercontent.com/epfl-dojo/contributors-trombinoscope/main/update-contributors.sh | bash

      # Runs a set of commands using the runners shell
      - name: commit README.md if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[auto] update contributors list"
          file_pattern: README.md
